AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend-taskhub-repo

  Sample SAM Template for Backend-taskhub-repo
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  ## Lambda Function
  GreetingsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sayHello
      Handler: index.lambdaHandler
      CodeUri: src/handlers/sayHello

  ## AppSync API
  TaskHubAppsyncApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: TaskHubAppsyncApi
      SchemaUri: src/schema.graphql
      DataSources:
        Lambda:
          GreetingsLambdaDataSource:
            Description: it will greet to the user
            FunctionArn: !GetAtt GreetingsLambdaFunction.Arn
      Functions:
        greetLambdaInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GreetingsLambdaDataSource
          InlineCode: |
            export function request(ctx) {
              return {
                operation: 'Invoke',
                payload: ctx.args
              };
            }

            export function response(ctx) {
              return ctx.result;
            }

      Auth:
        Type: OPENID_CONNECT
        OpenIDConnect:
          ClientId: 0oao20hif8aWVlBmZ5d7
          Issuer: https://dev-64276204.okta.com
        Additional:
          - Type: API_KEY
      ApiKeys:
        TaskHubAppsyncApiKey:
          Description: TaskHubAppsyncApiKey api key

      Resolvers:
        Query:
          sayHello:
            FieldName: sayHello
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - greetLambdaInvoker

Outputs:
  MyGraphQLAPI:
    Description: AppSync API
    Value: !GetAtt TaskHubAppsyncApi.GraphQLUrl
  MyGraphQLAPIMyApiKey:
    Description: API Key for authentication
    Value: !GetAtt TaskHubAppsyncApi.ApiId
