AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend-taskhub-repo

  Sample SAM Template for Backend-taskhub-repo

Resources:
  ## Lambda Function
  TaskHubLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambdaHandler
      Runtime: nodejs20.x
      CodeUri: src/
      MemorySize: 128
      Timeout: 10

  GreetingsResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TaskHubLambdaDataSource
    Properties:
      ApiId: !GetAtt TaskHubAppsyncApi.ApiId
      TypeName: Query
      FieldName: sayHello
      DataSourceName: TaskHubLambdaDataSource

  GetTasksByUserIdResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: TaskHubLambdaDataSource
    Properties:
      ApiId: !GetAtt TaskHubAppsyncApi.ApiId
      TypeName: Query
      FieldName: GetTasksByUserIdResolver
      DataSourceName: TaskHubLambdaDataSource

  AppsyncApikey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt TaskHubAppsyncApi.ApiId
      Expires: 1746057599

  ## AppSync API
  TaskHubAppsyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: TaskHubAppsyncApi
      AuthenticationType: API_KEY

  TaskHubGraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt TaskHubAppsyncApi.ApiId
      DefinitionS3Location: src/schema/schema.graphql

  ## Data Source - Lambda
  TaskHubLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt TaskHubAppsyncApi.ApiId
      Name: TaskHubLambdaDataSource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt TaskHubLambdaFunction.Arn
      ServiceRoleArn: !GetAtt TaskHubAppSyncLambdaRole.Arn

  ## IAM Role for AppSync to Invoke Lambda
  TaskHubAppSyncLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt TaskHubLambdaFunction.Arn
