AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend-taskhub-repo

  Sample SAM Template for Backend-taskhub-repo
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 128

Resources:
  ## Lambda Function
  TaskHubLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: taskhub-layer
      Description: Dependencies for the taskhub project
      ContentUri: lambdalayer/taskhubdependency
      CompatibleRuntimes:
        - nodejs20.x
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs20.x
      BuildArchitecture: arm64

  TaskHubLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: taskHubHandler
      Handler: index.taskHubApiHandler
      CodeUri: handlers/taskHandlers
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Scan
            Resource:
              - arn:aws:dynamodb:ap-south-1:977098988167:table/task
              - arn:aws:dynamodb:ap-south-1:977098988167:table/task/index/userid-index
      Layers:
        - !Ref TaskHubLambdaLayer

  ## AppSync API
  TaskHubAppsyncApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: TaskHubAppsyncApi
      SchemaUri: schema.graphql
      DataSources:
        Lambda:
          TaskHubLambdaDataSource:
            Description: it will greet to the user
            FunctionArn: !GetAtt TaskHubLambdaFunction.Arn
      Functions:
        TaskLambdaInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TaskHubLambdaDataSource
          CodeUri: gql/requestsAndResponse.mjs
      Auth:
        Type: OPENID_CONNECT
        OpenIDConnect:
          ClientId: n8nj3s96pr06h0eghdcun8qt2
          Issuer: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_x1WoxDDV3
        Additional:
          - Type: API_KEY
      ApiKeys:
        TaskHubAppsyncApiKey:
          Description: TaskHubAppsyncApiKey api key

      Resolvers:
        Query:
          sayHello:
            FieldName: sayHello
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - TaskLambdaInvoker
          getTasksByUserId:
            FieldName: getTasksByUserId
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - TaskLambdaInvoker
        Mutation:
          deleteTaskById:
            FieldName: deleteTaskById
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - TaskLambdaInvoker
          createTask:
            FieldName: createTask
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - TaskLambdaInvoker
Outputs:
  MyGraphQLAPI:
    Description: AppSync API
    Value: !GetAtt TaskHubAppsyncApi.GraphQLUrl
  MyGraphQLAPIMyApiKey:
    Description: API Key for authentication
    Value: !GetAtt TaskHubAppsyncApi.ApiId
