AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend-taskhub-repo

  Sample SAM Template for Backend-taskhub-repo
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  ## Lambda Function
  GreetingsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sayHello
      Handler: sayHello.SayHelloHandler
      CodeUri: src/handlers

  GetTasksByUserIdLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTasksByUserId
      Handler: getTasksByUserId.getTasksByUserIdHandler
      CodeUri: src/handlers
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Query
            Resource:
              - arn:aws:dynamodb:ap-south-1:977098988167:table/task
              - arn:aws:dynamodb:ap-south-1:977098988167:table/task/index/userid-index

  ## AppSync API
  TaskHubAppsyncApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: TaskHubAppsyncApi
      SchemaUri: src/schema.graphql
      DataSources:
        Lambda:
          GreetingsLambdaDataSource:
            Description: it will greet to the user
            FunctionArn: !GetAtt GreetingsLambdaFunction.Arn
          GetTaskByUserIdLambdaDataSource:
            Description: it will greet to the user
            FunctionArn: !GetAtt GetTasksByUserIdLambdaFunction.Arn
      Functions:
        greetLambdaInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GreetingsLambdaDataSource
          CodeUri: src/gql/greetings.js
        GetTasksByUseridInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetTaskByUserIdLambdaDataSource
          CodeUri: src/gql/getTasksByUserId.js
      Auth:
        Type: OPENID_CONNECT
        OpenIDConnect:
          ClientId: n8nj3s96pr06h0eghdcun8qt2
          Issuer: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_x1WoxDDV3
        Additional:
          - Type: API_KEY
      ApiKeys:
        TaskHubAppsyncApiKey:
          Description: TaskHubAppsyncApiKey api key

      Resolvers:
        Query:
          sayHello:
            FieldName: sayHello
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - greetLambdaInvoker
          getTasksByUserId:
            FieldName: getTasksByUserId
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
              - GetTasksByUseridInvoker

Outputs:
  MyGraphQLAPI:
    Description: AppSync API
    Value: !GetAtt TaskHubAppsyncApi.GraphQLUrl
  MyGraphQLAPIMyApiKey:
    Description: API Key for authentication
    Value: !GetAtt TaskHubAppsyncApi.ApiId
